# Server properties
server:
  port: 9091
  servlet:
    context-path: /pcs


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/pcsdb?createDatabaseIfNotExist=true
    password: Trzslgihr
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    #    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  sql:
    init:
      mode: always




