# Server properties
server:
  servlet:
    context-path: /pcs

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/pcsdb?createDatabaseIfNotExist=true
    password: '9696'
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: 'true'
  sql:
    init:
      mode: always


